<a href="https://colab.research.google.com/github/avnig309-dotcom/StockPricePrediction_project/blob/main/stock_prediciton_editing_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import yfinance as yf
import pandas as pd
#yfinance is a library and in this library the datasets have by default datetime as index
df = yf.download("^NSEI", period="max",auto_adjust=False)

[*********************100%***********************]  1 of 1 completed

In [2]:
df=df.iloc[::-1]
df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI
Date,,,,,,
2026-07-06,24430.349609,24430.349609,24458.650391,24287.099609,24306.849609,0
2026-07-03,24270.849609,24270.849609,24378.150391,24252.349609,24375.650391,326600
2026-07-02,24175.699219,24175.699219,24194.550781,24058.800781,24062.199219,372900
2026-07-01,24005.849609,24005.849609,24049.900391,23895.099609,23897.650391,352100
2026-06-30,23865.750000,23865.750000,24035.550781,23829.199219,24032.050781,449000

In [3]:
df["SMA20"]=df["Close"].rolling(window=20).mean()
df.head()

Price,Adj Close,Close,High,Low,Open,Volume,SMA20
Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,
Date,,,,,,,
2026-07-06,24430.349609,24430.349609,24458.650391,24287.099609,24306.849609,0,NaN
2026-07-03,24270.849609,24270.849609,24378.150391,24252.349609,24375.650391,326600,NaN
2026-07-02,24175.699219,24175.699219,24194.550781,24058.800781,24062.199219,372900,NaN
2026-07-01,24005.849609,24005.849609,24049.900391,23895.099609,23897.650391,352100,NaN
2026-06-30,23865.750000,23865.750000,24035.550781,23829.199219,24032.050781,449000,NaN

note that date appers neeche while price adj close etc appears above this indicates that date column is used as index.

also A ticker (or ticker symbol) is a unique short code used to identify a stock, index, ETF, or other financial instrument on a stock exchange.

example:-

Microsoft->MSFT,
Tesla->Inc.	TSLA,
Reliance Industries->RELIANCE (NSE),
Tata Consultancy Services->TCS,
NIFTY 50->^NSEI (in Yahoo Finance)

In [4]:
sub1=df.iloc[:20]#from start to 19=>0 to 19=>first 20
print(sub1)
print()
sub2=df.iloc[20:40]
print(sub2)

Price          Adj Close         Close          High           Low  \
Ticker             ^NSEI         ^NSEI         ^NSEI         ^NSEI
Date
2026-07-06  24430.349609  24430.349609  24458.650391  24287.099609
2026-07-03  24270.849609  24270.849609  24378.150391  24252.349609
2026-07-02  24175.699219  24175.699219  24194.550781  24058.800781
2026-07-01  24005.849609  24005.849609  24049.900391  23895.099609
2026-06-30  23865.750000  23865.750000  24035.550781  23829.199219
2026-06-29  23946.250000  23946.250000  24120.000000  23924.550781
2026-06-25  24056.000000  24056.000000  24261.599609  24039.000000
2026-06-24  24021.650391  24021.650391  24090.050781  23789.250000
2026-06-23  23824.099609  23824.099609  24135.500000  23784.949219
2026-06-22  24102.900391  24102.900391  24168.050781  24073.150391
2026-06-19  24013.099609  24013.099609  24047.199219  23901.900391
2026-06-18  24168.000000  24168.000000  24189.250000  24036.949219
2026-06-17  24085.699219  24085.699219  24108.199219  23969.699219
2026-06-16  23989.150391  23989.150391  24002.599609  23888.199219
2026-06-15  23853.900391  23853.900391  24011.400391  23817.800781
2026-06-12  23622.900391  23622.900391  23645.349609  23313.900391
2026-06-11  23161.599609  23161.599609  23327.449219  23072.050781
2026-06-10  23214.949219  23214.949219  23425.349609  23184.599609
2026-06-09  23242.099609  23242.099609  23279.400391  23104.449219
2026-06-08  23123.000000  23123.000000  23267.300781  23070.150391

Price               Open  Volume         SMA20
Ticker             ^NSEI   ^NSEI
Date
2026-07-06  24306.849609       0           NaN
2026-07-03  24375.650391  326600           NaN
2026-07-02  24062.199219  372900           NaN
2026-07-01  23897.650391  352100           NaN
2026-06-30  24032.050781  449000           NaN
2026-06-29  24061.750000  588500           NaN
2026-06-25  24125.849609  448800           NaN
2026-06-24  23795.800781  395600           NaN
2026-06-23  24071.300781  340100           NaN
2026-06-22  24106.599609  252800           NaN
2026-06-19  23991.199219  447900           NaN
2026-06-18  24073.800781  340000           NaN
2026-06-17  24044.500000  352700           NaN
2026-06-16  23923.900391  327300           NaN
2026-06-15  23984.849609  398900           NaN
2026-06-12  23412.550781  351900           NaN
2026-06-11  23104.400391  363000           NaN
2026-06-10  23233.949219  380000           NaN
2026-06-09  23259.050781  402600           NaN
2026-06-08  23080.699219  375700  23858.689844

Price          Adj Close         Close          High           Low  \
Ticker             ^NSEI         ^NSEI         ^NSEI         ^NSEI
Date
2026-06-05  23366.699219  23366.699219  23516.349609  23282.650391
2026-06-04  23416.550781  23416.550781  23465.300781  23247.300781
2026-06-03  23405.599609  23405.599609  23459.650391  23151.500000
2026-06-02  23483.550781  23483.550781  23556.949219  23229.150391
2026-06-01  23382.599609  23382.599609  23733.699219  23357.949219
2026-05-29  23547.750000  23547.750000  24002.800781  23484.750000
2026-05-27  23907.150391  23907.150391  23983.199219  23858.250000
2026-05-26  23913.699219  23913.699219  24089.800781  23885.449219
2026-05-25  24031.699219  24031.699219  24054.449219  23922.849609
2026-05-22  23719.300781  23719.300781  23835.650391  23671.000000
2026-05-21  23654.699219  23654.699219  23859.900391  23596.599609
2026-05-20  23659.000000  23659.000000  23690.900391  23397.300781
2026-05-19  23618.000000  23618.000000  23782.300781  23587.199219
2026-05-18  23649.949219  23649.949219  23695.650391  23317.099609
2026-05-15  23643.500000  23643.500000  23839.300781  23610.300781
2026-05-14  23689.599609  23689.599609  23777.199219  23426.550781
2026-05-13  23412.599609  23412.599609  23582.949219  23262.550781
2026-05-12  23379.550781  23379.550781  23757.550781  23348.400391
2026-05-11  23815.849609  23815.849609  23997.449219  23799.099609
2026-05-08  24176.150391  24176.150391  24253.800781  24126.650391

Price               Open   Volume         SMA20
Ticker             ^NSEI    ^NSEI
Date
2026-06-05  23478.949219   366200  23805.507324
2026-06-04  23282.449219   412500  23762.792383
2026-06-03  23415.949219   450100  23724.287402
2026-06-02  23229.150391   511900  23698.172461
2026-06-01  23654.500000   421700  23674.014941
2026-05-29  23902.150391  1198000  23654.089941
2026-05-27  23880.349609   531600  23646.647461
2026-05-26  24004.099609   387900  23641.249902
2026-05-25  23940.250000   351200  23651.629883
2026-05-22  23671.199219   336100  23632.449902
2026-05-21  23830.050781   348200  23614.529883
2026-05-20  23457.250000   344100  23589.079883
2026-05-19  23675.300781   442000  23565.694922
2026-05-18  23482.199219   392000  23548.734863
2026-05-15  23731.400391   408900  23538.214844
2026-05-14  23530.250000   428700  23541.549805
2026-05-13  23362.449219   415400  23554.099805
2026-05-12  23722.599609   447500  23562.329883
2026-05-11  23970.099609   390100  23591.017383
2026-05-08  24233.650391   335900  23643.674902

In [5]:
df["SMA50"]=df["Close"].rolling(window=50).mean()
print(df[["Close", "SMA50"]].iloc[45:55])

Price              Close         SMA50
Ticker             ^NSEI
Date
2026-04-29  24177.650391           NaN
2026-04-28  23995.699219           NaN
2026-04-27  24092.699219           NaN
2026-04-24  23897.949219           NaN
2026-04-23  24173.050781  23823.831914
2026-04-22  24378.099609  23822.786914
2026-04-21  24576.599609  23828.901914
2026-04-20  24364.849609  23832.684922
2026-04-17  24353.550781  23839.638945
2026-04-16  24196.750000  23846.258945

In [6]:
print(len(df))
print(df.columns)
print(df["Close"].head())

4610
MultiIndex([('Adj Close', '^NSEI'),
            (    'Close', '^NSEI'),
            (     'High', '^NSEI'),
            (      'Low', '^NSEI'),
            (     'Open', '^NSEI'),
            (   'Volume', '^NSEI'),
            (    'SMA20',      ''),
            (    'SMA50',      '')],
           names=['Price', 'Ticker'])
Ticker             ^NSEI
Date
2026-07-06  24430.349609
2026-07-03  24270.849609
2026-07-02  24175.699219
2026-07-01  24005.849609
2026-06-30  23865.750000

RN the database is multi-index.Database i.e=>two column levels.

In single index dataframes:-print(df.columns) looks like this=>

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

Multi-index looks like this:-

MultiIndex([('Adj Close', '^NSEI'),
            (    'Close', '^NSEI'),
            (     'High', '^NSEI'),
            (      'Low', '^NSEI'),
            (     'Open', '^NSEI'),
            (   'Volume', '^NSEI'),
            ])

now our dataframe is multi index (having two column levels) but along with that there is also a name featre added

names=['Price', 'Ticker']

isse ye pata chal rha ki jo pehla level of columns hai jisme low high etc hai uss levlel ke saare columns ka naam have been set to price

and jo dusra level hai ^NSEI wala uss level ke sare columns ka naam is ticker

note that we dont necessarily have names assigned to columns

so we are gonna remove the ticker column here coz sabka ticker is same ie ^NSEI and then we will only have one column toh column name rakhne ka bhi koi fayeda nhi hai so we will remove that as well

In [7]:
df.columns.names = [None, None]
df.columns=df.columns.droplevel(1)
print(df.iloc[50:100])

               Adj Close         Close          High           Low  \
Date
2026-04-22  24378.099609  24378.099609  24515.949219  24352.900391
2026-04-21  24576.599609  24576.599609  24601.699219  24354.900391
2026-04-20  24364.849609  24364.849609  24480.650391  24241.250000
2026-04-17  24353.550781  24353.550781  24371.900391  24096.050781
2026-04-16  24196.750000  24196.750000  24400.949219  24102.800781
2026-04-15  24231.300781  24231.300781  24280.900391  24145.800781
2026-04-13  23842.650391  23842.650391  23907.400391  23555.599609
2026-04-10  24050.599609  24050.599609  24074.050781  23856.349609
2026-04-09  23775.099609  23775.099609  23990.750000  23682.800781
2026-04-08  23997.349609  23997.349609  24025.150391  23828.500000
2026-04-07  23123.650391  23123.650391  23153.849609  22719.300781
2026-04-06  22968.250000  22968.250000  22998.349609  22542.949219
2026-04-02  22713.099609  22713.099609  22782.300781  22182.550781
2026-04-01  22679.400391  22679.400391  22941.300781  22618.599609
2026-03-30  22331.400391  22331.400391  22714.099609  22283.849609
2026-03-27  22819.599609  22819.599609  23186.099609  22804.550781
2026-03-25  23306.449219  23306.449219  23465.349609  23063.199219
2026-03-24  22912.400391  22912.400391  23057.300781  22624.199219
2026-03-23  22512.650391  22512.650391  22851.699219  22471.250000
2026-03-20  23114.500000  23114.500000  23345.150391  23067.599609
2026-03-19  23002.150391  23002.150391  23378.699219  22930.349609
2026-03-18  23777.800781  23777.800781  23862.250000  23618.449219
2026-03-17  23581.150391  23581.150391  23656.800781  23346.599609
2026-03-16  23408.800781  23408.800781  23502.000000  22955.250000
2026-03-13  23151.099609  23151.099609  23492.400391  23112.000000
2026-03-12  23639.150391  23639.150391  23833.150391  23556.300781
2026-03-11  23866.849609  23866.849609  24299.000000  23834.300781
2026-03-10  24261.599609  24261.599609  24303.800781  24079.949219
2026-03-09  24028.050781  24028.050781  24078.150391  23697.800781
2026-03-06  24450.449219  24450.449219  24700.900391  24415.750000
2026-03-05  24765.900391  24765.900391  24854.199219  24529.400391
2026-03-04  24480.500000  24480.500000  24602.449219  24305.400391
2026-03-02  24865.699219  24865.699219  24989.349609  24603.500000
2026-02-27  25178.650391  25178.650391  25476.400391  25141.300781
2026-02-26  25496.550781  25496.550781  25572.949219  25400.949219
2026-02-25  25482.500000  25482.500000  25652.599609  25428.199219
2026-02-24  25424.650391  25424.650391  25641.800781  25327.599609
2026-02-23  25713.000000  25713.000000  25771.449219  25609.349609
2026-02-20  25571.250000  25571.250000  25663.550781  25379.750000
2026-02-19  25454.349609  25454.349609  25885.300781  25388.750000
2026-02-18  25819.349609  25819.349609  25828.050781  25645.150391
2026-02-17  25725.400391  25725.400391  25764.400391  25570.300781
2026-02-16  25682.750000  25682.750000  25697.000000  25372.699219
2026-02-13  25471.099609  25471.099609  25630.349609  25444.300781
2026-02-12  25807.199219  25807.199219  25906.699219  25752.400391
2026-02-11  25953.849609  25953.849609  26009.400391  25899.800781
2026-02-10  25935.150391  25935.150391  25989.449219  25870.449219
2026-02-09  25867.300781  25867.300781  25922.250000  25780.900391
2026-02-06  25693.699219  25693.699219  25703.949219  25491.900391
2026-02-05  25642.800781  25642.800781  25757.650391  25579.500000

                    Open  Volume         SMA20         SMA50
Date
2026-04-22  24470.849609  440500  23928.329980  23822.786914
2026-04-21  24374.550781  425800  23974.209961  23828.901914
2026-04-20  24391.500000  415900  24011.552441  23832.684922
2026-04-17  24165.900391  498600  24046.732520  23839.638945
2026-04-16  24385.199219  508000  24074.395020  23846.258945
2026-04-15  24163.800781  460300  24101.480078  23851.959961
2026-04-13  23589.599609  488800  24122.982617  23847.692969
2026-04-10  23880.550781  481300  24156.535059  23848.271953
2026-04-09  23909.050781  466600  24154.497559  23847.291953
2026-04-08  23855.150391  639300  24145.557520  23845.180938
2026-04-07  22838.699219  477000  24085.407520  23827.391953
2026-04-06  22780.300781  426400  24017.272559  23803.396953
2026-04-02  22383.400391  495100  23951.287500  23775.944961
2026-04-01  22899.000000  518000  23879.292480  23749.749961
2026-03-30  22549.650391  698600  23795.984961  23719.299961
2026-03-27  23173.550781  612600  23728.082422  23703.233945
2026-03-25  23064.400391  505400  23693.619922  23706.130937
2026-03-24  22878.449219  538100  23634.604980  23700.079961
2026-03-23  22824.349609  550300  23565.340039  23685.490977
2026-03-20  23110.150391  663300  23512.412500  23685.320977
2026-03-19  23197.750000  550100  23443.615039  23678.030000
2026-03-18  23632.900391  382900  23403.675098  23685.255000
2026-03-17  23493.199219  458800  23364.490137  23688.766016
2026-03-16  23116.099609  540300  23317.252637  23687.271016
2026-03-13  23462.500000  519800  23264.970117  23682.641016
2026-03-12  23674.849609  501000  23235.362598  23684.469023
2026-03-11  24231.849609  407400  23236.572559  23683.663008
2026-03-10  24280.800781  444300  23247.122559  23690.621016
2026-03-09  23868.050781  526900  23259.770117  23690.548047
2026-03-06  24656.400391  433400  23282.425098  23705.171016
2026-03-05  24615.949219  504300  23364.537598  23727.395039
2026-03-04  24388.800781  599000  23440.150098  23743.825039
2026-03-02  24659.250000  519200  23547.780078  23768.779023
2026-02-27  25459.849609  438900  23672.742578  23799.353047
2026-02-26  25556.300781  405200  23831.000098  23836.414062
2026-02-25  25512.599609  414200  23964.145117  23872.272070
2026-02-24  25641.800781  439100  24070.055176  23912.513086
2026-02-23  25678.400391  313700  24210.085156  23959.182070
2026-02-20  25406.550781  296600  24363.015137  23994.290078
2026-02-19  25873.349609  298200  24480.007617  24019.854062
2026-02-18  25752.650391  310200  24620.867578  24049.708047
2026-02-17  25637.949219  344100  24718.247559  24077.597070
2026-02-16  25423.599609  275800  24823.327539  24110.596055
2026-02-13  25571.150391  453500  24926.442480  24137.632031
2026-02-12  25906.699219  419400  25059.247461  24173.825000
2026-02-11  25997.449219  331400  25174.982422  24209.348984
2026-02-10  25922.650391  460900  25278.397461  24248.138008
2026-02-09  25888.699219  359400  25358.682520  24283.630039
2026-02-06  25605.800781  375500  25441.964941  24319.545039
2026-02-05  25755.900391  343800  25501.582520  24348.940039